import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Client } from '@notionhq/client'

type article = {
  title:string;
  description:string
}

export async function getStaticProps (){

  const token = "secret_racnnx6eQriOuQ2Df1EGAXz0UDDplG84ahEDtWm0Sgo";
  const databaseId = "ffee93b713ed43a7980443ec527f6056";

  const notion = new Client({ auth: token })
  const  data = await notion.databases.query({ database_id : databaseId});

  const articleList: article[] = data.results
  .map((_:any)=>_.properties)
  .map((_)=>{
    return {
      title : _.title.title[0].plain_text,
      description : _.description.rich_text[0].plain_text,
    };
  });

  console.log(data)
  // const articleList : article[] = [
  //   {title:"見出し1",description:"本文1"},
  //   {title:"見出し2",description:"本文2"},
  //   {title:"見出し3",description:"本文3"},
  //   {title:"見出し4",description:"本文4"},
  // ];
  return { props:{articleList}, revalidate: 30};
};

type Props = {
  articleList:article[]
};

export default function Home({articleList}:Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Blog</a>
        </h1>
        <p className={styles.description}>
          Notion Apiと連携したブログです
        </p>
        <div className={styles.grid}>
          {articleList.map((_:any)=>(
             <a href="https://www.google.co.jp/" className={styles.card}>
             <h2 >{_.title}</h2>
             <p>{_.description}</p>
           </a>
          ))}
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}